export const prefixes = {
  argentina: '54',
  bolivia: '591',
  brazil: '55',
  chile: '56',
  colombia: '57',
  mexico: '521',
  peru: '51',
  spain: '34',
  uruguay: '598',
  portugal: '351',
  ecuador: '593',
  panama: '507',
  costarica: '506',
  dominican: '1',
  japan: '81',
};

export const countryCodes = {
  spain: 'ES',
  chile: 'CL',
  mexico: 'MX',
  colombia: 'CO',
  peru: 'PE',
  argentina: 'AR',
  brazil: 'BR',
  bolivia: 'BO',
  uruguay: 'UY',
  portugal: 'PT',
  ecuador: 'EC',
  panama: 'PA',
  costarica: 'CR',
  dominican: 'DO',
  japan: 'JP',
};

export const countries = [
  { name: 'Argentina', prefix: prefixes.argentina, countryCode: countryCodes.argentina },
  { name: 'Bolivia', prefix: prefixes.bolivia, countryCode: countryCodes.bolivia },
  { name: 'Brazil', prefix: prefixes.brazil, countryCode: countryCodes.brazil },
  { name: 'Chile', prefix: prefixes.chile, countryCode: countryCodes.chile },
  { name: 'Colombia', prefix: prefixes.colombia, countryCode: countryCodes.colombia },
  { name: 'Mexico', prefix: prefixes.mexico, countryCode: countryCodes.mexico },
  { name: 'Peru', prefix: prefixes.peru, countryCode: countryCodes.peru },
  { name: 'Spain', prefix: prefixes.spain, countryCode: countryCodes.spain },
  { name: 'Uruguay', prefix: prefixes.uruguay, countryCode: countryCodes.uruguay },
  { name: 'Portugal', prefix: prefixes.portugal, countryCode: countryCodes.portugal },
  { name: 'Ecuador', prefix: prefixes.ecuador, countryCode: countryCodes.ecuador },
  { name: 'Panama', prefix: prefixes.panama, countryCode: countryCodes.panama },
  { name: 'Costa Rica', prefix: prefixes.costarica, countryCode: countryCodes.costarica },
  { name: 'Dominican Republic', prefix: prefixes.dominican, countryCode: countryCodes.dominican },
  { name: 'Japan', prefix: prefixes.japan, countryCode: countryCodes.japan },
];
